// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lzwhrcllsdzzewdwmetu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6d2hyY2xsc2R6emV3ZHdtZXR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1Mjk1MTQsImV4cCI6MjA2MDEwNTUxNH0.co3KTTNPuA70lJgFuLlWqo-brHI5qg6j7rRs8XmoAz8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);